version: '3'

volumes:
  postgres:
    
networks:
  default:
    driver: bridge

services:
  db:
    image: postgres:10
    restart: always
    environment:
       POSTGRES_PASSWORD: DatabasePassword 
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#   network_mode: "host"
    networks:
      - default
    depends_on:
      - db
      - app

  app:
    build: app/
    #    expose:
    #      - 7000
    ports:
      - "7000:7000"
    environment:
            # PGDATABASE: postgres
            #       PGUSER: postgres
            #       PGPASSWORD: DatabasePassword
       POSTGRES_URI: postgres://postgres:DatabasePassword@db/postgres?sslmode=disable
       LISTEN_ADDRESS: :7000
    networks:
      - default
       #    links:
       #      - db
    depends_on:
      - db
