version: '3.8'

services:

  traefik:
    image: traefik:v2.4
    ports:
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
             - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker.swarmmode
      - --api.insecure=true
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
