version: '3.8'

services:
    fluentd:
      image: registry.rebrainme.com/docker_users_repos/1332/dkr-30-voting/fluentd
      volumes:
         - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf 
      links:
         - "elasticsearch"
      ports:
         - "24224:24224"
         - "24224:24224/udp"
      deploy:
         mode: replicated
         replicas: 3
         placement:
             constraints:
                - node.role == manager
      networks:
         - traefik-public

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1   
      environment:
         - "discovery.type=single-node"
         - "bootstrap.memory_lock=true"
         - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      expose:
         - 9200
      ports:
         - "9200:9200"
      volumes:
              #         - vol:/var/lib/elasticsearch/nodes/0
         - vol:/usr/share/elasticsearch/data/nodes/0
      networks:
         - traefik-public

    kibana:
      image: docker.elastic.co/kibana/kibana:7.13.1
      links:
         - "elasticsearch"
      ports:
         - "5601:5601"
      deploy:
         mode: replicated
         labels:
           - "traefik.enable=true"
           - "traefik.http.routers.kibana.rule=Host(`kibana.167.71.50.185.nip.io`, `kibana.167.71.50.149.nip.io`, `kibana.167.71.58.35.nip.io`)"
           - "traefik.http.routers.kibana.middlewares=auth"
           - "traefik.http.middlewares.auth.basicauth.users=rebrainme:$$apr1$$8PZ1iUp8$$Pvbs6feOnyC4ofSNeySEi1"
           - "traefik.http.services.kibana.loadbalancer.server.port=5601"
      depends_on:
         - elasticsearch
      networks:
         - traefik-public

networks:
  traefik-public:
    external: true

volumes:
    vol:
      driver: glusterfs
      name: "gfs/volume"


